### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by githubteacher** [githubschool/github-games-amang2205#1]
When attempting to access this at https://githubschool.github.io/github-games-amang2205, I am getting a 404. This could be caused by a couple things:

 - GitHub pages needs to be enabled on master. You can fix this in the repository settings.
- the index.html file is incorrectly named inde.html. We will fix this together in class.

 Can you please fix the first bullet @amang2205?

**Comment by amang2205** [comment]
I’m lost…

**Comment by amang2205** [comment]
So I believe I did both, yet the page doesn't yet show up - still shows a 404. Am I doing something wrong, @githubteacher ?

**Comment by amang2205** [comment]
P.S.: I love it that I can reply to this discussion straight from my e-mail client. Would be nice if the extra clutter would be left out, but of course I (as a user) should delete the clutter data in the e-mail.

**Comment by amang2205** [comment]
Should be fixed now.
